version: "3"
services:
  app:
    build: .
    container_name: menu_gateway
    command: >-
      sh -c "
        apk add php8-pecl-xdebug && composer install ;\
        cp .docker/xdebug.ini /etc/php8/conf.d/50_xdebug.ini ;\
        php -S localhost:8000 -t public"
    ports:
      - "8001:80"
    env_file:
      - .env
    volumes:
      - .docker/xdebug.ini
      - .:/var/www/html:rw
    networks:
      - app_network

  mysql:
    image: mysql:8
    container_name: menu_gateway_db
    ports:
      - "3307:3306"
    restart: "no"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: menu_gateway_cache
    ports:
      - "6380:6379"
    volumes:
     - cache_data:/data
    networks:
      - app_network

volumes:
  db_data:
    driver: "local"
  cache_data:
    driver: "local"

networks:
  app_network:
    driver: "bridge"
